### ISSUE TITLE
Sponsor Page

### ISSUE THREAD

**Issue by kevinprince** [hackedio/website#19]
On branch logos are added to RHS for frontpage

Sponsor page needs to be fleshed out and details about sponsoring

**Comment by kevinprince** [comment]
Added sponsors but they each need a bio. 

@cbetta can you add your bits to the bottom.

**Comment by tommorris** [comment]
Do the sponsor descriptions need to be written by us or by the sponsors? Can they just be nicked from the sponsor websites?

**Comment by kevinprince** [comment]
Waiting for them from sponsors
